POST http://localhost:3000/company/register
Content-Type: application/json

{
    "name": "Microsoft",
    "email": "microsoft@interia.pl",
    "country": "Poland",
    "target": "Our mission is to empower every person and every organization on the planet to achieve more. Learn more about our company, who we are and what we value",
    "description": "Innovation, dependable technology, equality and diversity, corporate social responsibility, philanthropies, and the environment",
    "whoWeWant": "help people",
    "tags": ["i", "am"]
}