POST http://localhost:3000/foundation/register
Content-Type: application/json

{
    "name": "German Cancer Aid",
    "email": "krebshilfe@infonetz-krebs.de",
    "country": "Germany",
    "target": "Cancer fighting international non-profit organisation",
    "projects": "We've helped a lot of people with different types of cancer in the past"
}