POST http://localhost:3000/foundation/register
Content-Type: application/json

{
    "name": "niepomagajmy",
    "email": "example@outlook.com",
    "country": "Poland",
    "target": "We are supporting biggest hospitals in poland by providing medical resources",
    "projects": "We are making our grand-final's events where we are collecting money",
    "description": "Jerzy Owsiak is our owner"
}