POST http://localhost:3000/fundingRequest/
Content-Type: application/json

{
    "title": "Donate new volleyball pitch",
    "target": "help poor children to be better in volleyball",
    "description": "We want to invest into volleyball",
    "FoundationId": 2
}